---
##############################
# Rules (With config) created by CallumRawlinson
##############################


#Add rules below
#You may also use some of the staff slots as a title slot
rule1: "Example"
rule2: "Example"
rule3: "Example"
rule4: "Example"
rule5: "Example"
rule6: "Example"
rule7: "Example"
rule8: "Example"
...
